### ISSUE TITLE
[feature request] please support github enterprise

### ISSUE THREAD

**Issue by emacsbliss** [blahgeek/emacs-pr-review#2]
this looks great, if would be really nice if it can support github enterprise which has custom domain name.

**Comment by blahgeek** [comment]
Hi,

This should be easy to support, but I don't have access to any github enterprise service for testing. Can you provide more information? Is it sufficient to replace `api.github.com` with some custom domain?

**Comment by emacsbliss** [comment]
extracting the api.github.com out to make it customizable will definitely help, but I'm not sure that's all.

for eg, something like this https://github.com/blahgeek/emacs-pr-review/blob/master/pr-review-api.el#L88 may also need change?

**Comment by blahgeek** [comment]
supported in https://github.com/blahgeek/emacs-pr-review/commit/a4f747de1922f5f4142ea8be491ae7b06a05d3a4
